[build]
    command = "hugo"
    publish = "public"

[dev]
    framework = "hugo"
    command = "hugo server"

[[plugins]]
    package = "netlify-plugin-submit-sitemap"
    [plugins.inputs]
        baseUrl = "https://hexandcube.eu.org"
        sitemapPath = "/sitemap.xml"

[[redirects]]
    from = "/*"
    to = "/404"
    status = 404
    force = false