[build]
    command = "hugo"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.139.2"

[dev]
    framework = "hugo"
    command = "hugo server"

[[redirects]]
    from = "/*"
    to = "/404"
    status = 404
    force = false

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    Content-Type="application/json"
