backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/img/uploads"
display_url: https://hexandcube.eu.org
logo_url: https://files.hexandcube.eu.org/images/Logo-color.png

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Hexandcube"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "publishDate", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "wallpapers"
    label: "Wallpapers"
    folder: "content/wallpapers"
    create: true
    slug: "wallpaper-{{id}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Wallpaper"}
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Variant", name: "variant", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Keywords", name: "keywords", widget: "string"}
      - {label: "Resolution", name: "resolution", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "photos"
    label: "Photos"
    folder: "content/photos"
    create: true
    slug: "{{id}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "ID", name: "id", widget: "string"}
      - {label: "License", name: "license", widget: "string"}
      - {label: "License URL", name: "licenseUrl", widget: "string"}
      - {label: "Resolution", name: "resolution", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Camera", name: "camera", widget: "string"}
      - {label: "Lens", name: "lens", widget: "string"}
      - {label: "ISO", name: "iso", widget: "string"}
      - {label: "Focal Length", name: "focalLength", widget: "string"}
      - {label: "Shutter Speed", name: "shutterSpeed", widget: "string"}
      - {label: "Aperture", name: "aperture", widget: "string", default: "f/"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "files"
    label: "Files"
    folder: "content/files"
    create: true
    slug: "{{slug}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "File Name", name: "fileName", widget: "string"}
      - {label: "File Type", name: "fileType", widget: "string"}
      - {label: "File Size", name: "fileSize", widget: "string"}
      - {label: "File Version", name: "fileVersion", widget: "string"}
      - {label: "File Date", name: "fileDate", widget: "datetime"}
      - {label: "Icon", name: "icon", widget: "string", default: "fa-file"}
      - {label: "Download URL", name: "download", widget: "string"}
      - {label: "Download Server", name: "downloadServer", widget: "string"}
      - {label: "Servers", name: "servers", widget: "list", fields: [{label: "Name", name: "name"}, {label: "Download", name: "download"}]}
      - {label: "Versions", name: "versions", widget: "list", fields: [{label: "Name", name: "name"}, {label: "Download", name: "download"}, {label: "Date", name: "date", widget: "datetime"}]}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Hide Metabar", name: "hideMetabar", widget: "boolean"}
      - {label: "Hide Reading Time", name: "hideReadingTime", widget: "boolean"}
      - {label: "Author", name: "author", widget: "string", default: "Hexandcube"}
      - {label: "Date", name: "publishDate", widget: "datetime"}
      - {label: "Last Modified", name: "lastmod", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}